### ISSUE TITLE
undefined symbol errors on extension import

### ISSUE THREAD

**Issue by alisterburt** [rosalindfranklininstitute/amplus-digital-twin#6]
Sorry to bring more problems so soon! I'm getting undefined symbol errors, I assume this is some mismatch between the compiled extension and python?

I'm running in a conda environment with python 3.9 - will try with your venv setup on scarf but it still feels like this should work so I thought I'd raise an issue
```sh
(parakeet) [scarf1041@cn304 ~]$ parakeet.config.show
Traceback (most recent call last):
  File "/home/vol01/scarf1041/programs/miniconda3/envs/parakeet/bin/parakeet.config.show", line 5, in <module>
    from parakeet.command_line.config import show
  File "/home/vol01/scarf1041/programs/miniconda3/envs/parakeet/lib/python3.9/site-packages/parakeet/command_line/__init__.py", line 19, in <module>
    import parakeet.sample
  File "/home/vol01/scarf1041/programs/miniconda3/envs/parakeet/lib/python3.9/site-packages/parakeet/sample.py", line 22, in <module>
    import parakeet.freeze
  File "/home/vol01/scarf1041/programs/miniconda3/envs/parakeet/lib/python3.9/site-packages/parakeet/freeze/__init__.py", line 17, in <module>
    from parakeet_ext import *  # noqa
ImportError: /home/vol01/scarf1041/programs/miniconda3/envs/parakeet/lib/python3.9/site-packages/parakeet_ext.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZTVN10__cxxabiv117__class_type_infoE
```

**Comment by alisterburt** [comment]
unfortunately, the same error persists when working in a virtual environment setup the way you described

**Comment by jmp1985** [comment]
Hi Alister,

This is my bad, I used gcc where I should have used g++!

I compiled and tested with the following commands and hopefully this should work. I have also updated the README with some better instructions for setting the CXX and CUDACXX environment variables.

# Load necessary modules
module load Anaconda3
module load GPUmodules
module load CUDA/11.1.1-GCC-10.2.0
module load gcc/7.2.0

# Lets export the compilers to use
export CXX=$(which g++)
export CUDACXX=$(which nvcc)

# Setup python3 environment
conda create --name test-env-parakeet python=3.8
conda activate test-env-parakeet

# Install and test
git clone https://github.com/rosalindfranklininstitute/amplus-digital-twin.git
pushd amplus-digital-twin
git submodule --init --recursive
python -m pip install -e .
python -m pip install pytest pytest-cov
python -m pytest
popd

**Comment by alisterburt** [comment]
excellent! thanks so much for this, small modification required here:
`git submodule --init --recursive` -> `git submodule update --init --recursive`

I'm getting some test failures on current master, do these look like something I should be worried about?
```sh
===================================== short test summary info =====================================
FAILED tests/test_amplus.py::test_simulate_exit_wave - NameError: name 'multem' is not defined
FAILED tests/test_amplus.py::test_simulate_optics - NameError: name 'multem' is not defined
FAILED tests/test_slice.py::test_slice - NameError: name 'multem' is not defined
```

**Comment by jmp1985** [comment]
Hi Alistair, are you still getting this error?

When I ran through these instructions automatically from scratch the following error occurred which resulted in the install and tests failing. After running the conda activate command I got the error:

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```
Running `conda init bash` and then closing the terminal and running conda activate and the following commands again seemed to work for me. All the tests should pass so if something is failing that would indicate a problem!

**Comment by alisterburt** [comment]
Hi James,

I'm using my own conda install so didn't have that issue - I have managed to simulate some data using the test molecules in your config file (woo!) so everything seems to be working as it should be :) I emailed you a question about loading external data rather than using the test molecules, I'm sure you're working through the backlog if you've been away, no rush from my side!
